/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRiskRouteImport } from './routes/onboarding.risk'
import { Route as OnboardingNameRouteImport } from './routes/onboarding.name'
import { Route as OnboardingKnowledgeRouteImport } from './routes/onboarding.knowledge'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding.goal'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as InvestSuccessRouteImport } from './routes/invest.success'
import { Route as InvestReviewRouteImport } from './routes/invest.review'
import { Route as InvestConfirmRouteImport } from './routes/invest.confirm'

const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRiskRoute = OnboardingRiskRouteImport.update({
  id: '/onboarding/risk',
  path: '/onboarding/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNameRoute = OnboardingNameRouteImport.update({
  id: '/onboarding/name',
  path: '/onboarding/name',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingKnowledgeRoute = OnboardingKnowledgeRouteImport.update({
  id: '/onboarding/knowledge',
  path: '/onboarding/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const InvestSuccessRoute = InvestSuccessRouteImport.update({
  id: '/invest/success',
  path: '/invest/success',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestReviewRoute = InvestReviewRouteImport.update({
  id: '/invest/review',
  path: '/invest/review',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestConfirmRoute = InvestConfirmRouteImport.update({
  id: '/invest/confirm',
  path: '/invest/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/simulate': typeof SimulateRoute
  '/invest/confirm': typeof InvestConfirmRoute
  '/invest/review': typeof InvestReviewRoute
  '/invest/success': typeof InvestSuccessRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/knowledge': typeof OnboardingKnowledgeRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/risk': typeof OnboardingRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/simulate': typeof SimulateRoute
  '/invest/confirm': typeof InvestConfirmRoute
  '/invest/review': typeof InvestReviewRoute
  '/invest/success': typeof InvestSuccessRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/knowledge': typeof OnboardingKnowledgeRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/risk': typeof OnboardingRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/simulate': typeof SimulateRoute
  '/invest/confirm': typeof InvestConfirmRoute
  '/invest/review': typeof InvestReviewRoute
  '/invest/success': typeof InvestSuccessRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/knowledge': typeof OnboardingKnowledgeRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/risk': typeof OnboardingRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/learn'
    | '/portfolio'
    | '/profile'
    | '/simulate'
    | '/invest/confirm'
    | '/invest/review'
    | '/invest/success'
    | '/learn/$slug'
    | '/onboarding/goal'
    | '/onboarding/knowledge'
    | '/onboarding/name'
    | '/onboarding/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/learn'
    | '/portfolio'
    | '/profile'
    | '/simulate'
    | '/invest/confirm'
    | '/invest/review'
    | '/invest/success'
    | '/learn/$slug'
    | '/onboarding/goal'
    | '/onboarding/knowledge'
    | '/onboarding/name'
    | '/onboarding/risk'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/learn'
    | '/portfolio'
    | '/profile'
    | '/simulate'
    | '/invest/confirm'
    | '/invest/review'
    | '/invest/success'
    | '/learn/$slug'
    | '/onboarding/goal'
    | '/onboarding/knowledge'
    | '/onboarding/name'
    | '/onboarding/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  LearnRoute: typeof LearnRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  SimulateRoute: typeof SimulateRoute
  InvestConfirmRoute: typeof InvestConfirmRoute
  InvestReviewRoute: typeof InvestReviewRoute
  InvestSuccessRoute: typeof InvestSuccessRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingKnowledgeRoute: typeof OnboardingKnowledgeRoute
  OnboardingNameRoute: typeof OnboardingNameRoute
  OnboardingRiskRoute: typeof OnboardingRiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/risk': {
      id: '/onboarding/risk'
      path: '/onboarding/risk'
      fullPath: '/onboarding/risk'
      preLoaderRoute: typeof OnboardingRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/name': {
      id: '/onboarding/name'
      path: '/onboarding/name'
      fullPath: '/onboarding/name'
      preLoaderRoute: typeof OnboardingNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/knowledge': {
      id: '/onboarding/knowledge'
      path: '/onboarding/knowledge'
      fullPath: '/onboarding/knowledge'
      preLoaderRoute: typeof OnboardingKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/invest/success': {
      id: '/invest/success'
      path: '/invest/success'
      fullPath: '/invest/success'
      preLoaderRoute: typeof InvestSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/review': {
      id: '/invest/review'
      path: '/invest/review'
      fullPath: '/invest/review'
      preLoaderRoute: typeof InvestReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/confirm': {
      id: '/invest/confirm'
      path: '/invest/confirm'
      fullPath: '/invest/confirm'
      preLoaderRoute: typeof InvestConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  LearnRoute: LearnRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  SimulateRoute: SimulateRoute,
  InvestConfirmRoute: InvestConfirmRoute,
  InvestReviewRoute: InvestReviewRoute,
  InvestSuccessRoute: InvestSuccessRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingKnowledgeRoute: OnboardingKnowledgeRoute,
  OnboardingNameRoute: OnboardingNameRoute,
  OnboardingRiskRoute: OnboardingRiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
